"""
Django settings for edutrellis project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

_gemma_key_file = BASE_DIR / '.secrets' / 'nvidia_gemma_api_key'
# Backs the "Gemini 3.6 Flash" picker option (myapp/ai_chat.py), which calls
# google/gemma-4-31b-it on NVIDIA NIM. Same hardcoding trade-off as the other
# keys in this file — intentionally hardcoded at the project owner's request.
NVIDIA_GEMMA_API_KEY = os.environ.get(
    'NVIDIA_GEMMA_API_KEY',
    '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',
).strip()
if not NVIDIA_GEMMA_API_KEY and _gemma_key_file.is_file():
    NVIDIA_GEMMA_API_KEY = _gemma_key_file.read_text(encoding='utf-8').strip()

# Full FLUX NIM inference URL accepting uploaded images (not the preview API).
FLUX_EDIT_API_URL = os.environ.get('FLUX_EDIT_API_URL', '').strip()
FLUX_EDIT_API_KEY = os.environ.get('FLUX_EDIT_API_KEY', '').strip()

QWEN_IMAGE_EDIT_API_URL = os.environ.get('QWEN_IMAGE_EDIT_API_URL', '').strip()
QWEN_IMAGE_EDIT_ENDPOINT_KEY = os.environ.get('QWEN_IMAGE_EDIT_ENDPOINT_KEY', '').strip()
_qwen_image_key_file = BASE_DIR / '.secrets' / 'nvidia_qwen_image_edit_api_key'
NVIDIA_QWEN_IMAGE_EDIT_API_KEY = os.environ.get('NVIDIA_QWEN_IMAGE_EDIT_API_KEY', '').strip()
if not NVIDIA_QWEN_IMAGE_EDIT_API_KEY and _qwen_image_key_file.is_file():
    NVIDIA_QWEN_IMAGE_EDIT_API_KEY = _qwen_image_key_file.read_text(encoding='utf-8').strip()

_kontext_key_file = BASE_DIR / '.secrets' / 'nvidia_flux_kontext_api_key'
NVIDIA_FLUX_KONTEXT_API_KEY = os.environ.get('NVIDIA_FLUX_KONTEXT_API_KEY', '').strip()
if not NVIDIA_FLUX_KONTEXT_API_KEY and _kontext_key_file.is_file():
    NVIDIA_FLUX_KONTEXT_API_KEY = _kontext_key_file.read_text(encoding='utf-8').strip()

# Local credentials stay outside version control; deployments can use env vars.
_gpt_oss_key_file = BASE_DIR / '.secrets' / 'nvidia_gpt_oss_api_key'
NVIDIA_GPT_OSS_API_KEY = os.environ.get('NVIDIA_GPT_OSS_API_KEY', '').strip()
if not NVIDIA_GPT_OSS_API_KEY and _gpt_oss_key_file.is_file():
    NVIDIA_GPT_OSS_API_KEY = _gpt_oss_key_file.read_text(encoding='utf-8').strip()

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-2!^^*c(t)whrn^4w3xkoqx!1p85e5s!-xh0w+xai7&q*80tt@@'
)

DEBUG = True

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'myapp.apps.MyappConfig',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'myapp.middleware.CanonicalHostMiddleware',
    'myapp.middleware.PublicAssetCacheMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'myapp.middleware.SingleDeviceSessionMiddleware',
    'myapp.middleware.HideAdminFromNonStaffMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edutrellis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.business_info.context_processor',
                'myapp.views.site_customization_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'edutrellis.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'myapp' / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default Django session lifetime is 2 weeks, counted from creation — an
# anonymous visitor's cart/AI chat history (both keyed off session_key) would
# silently become unreachable after that, since a new session (and therefore
# a new, empty session_key) gets created on their next visit. Extending this
# to a year and refreshing it on every request means a returning guest keeps
# their data as long as they visit at least once a year, without needing an
# account.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365
SESSION_SAVE_EVERY_REQUEST = True

# GitHub OAuth App credentials for the /AI/ GitHub-mode "Login with GitHub"
# button (myapp/views.py github_oauth_start/callback). Register an OAuth App
# at https://github.com/settings/developers with its Authorization callback
# URL set to <your domain>/AI/api/github/oauth/callback/, then set these two
# env vars. Left unset, the connect panel just falls back to pasting a
# Personal Access Token — nothing breaks, the button simply doesn't appear.
GITHUB_OAUTH_CLIENT_ID = os.environ.get('GITHUB_OAUTH_CLIENT_ID', '')
GITHUB_OAUTH_CLIENT_SECRET = os.environ.get('GITHUB_OAUTH_CLIENT_SECRET', '')

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True




# ── Email (Gmail SMTP via App Password) ─────────────────────────────────────
# All outbound store/site email (order confirmations, contact-lead alerts) is
# sent via this account. Signup/profile verification codes moved to SMS (see
# TWO_FACTOR_API_KEY below) — email is no longer in that path. The
# dashboard's Email Settings page has been deactivated — this is the only
# email path now. Hardcoded on purpose, with NO os.environ.get() indirection
# — a stale EMAIL_HOST_USER/PASSWORD env var left over from earlier SMTP
# testing on a dev machine would otherwise silently override these and
# nobody would know.

EMAIL_BACKEND  = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST     = 'smtp.gmail.com'
EMAIL_PORT     = 587
EMAIL_USE_TLS  = True
EMAIL_USE_SSL  = False

# Fail fast rather than hanging the request for 30+ seconds if Gmail's SMTP
# doesn't respond within 10 seconds.
EMAIL_TIMEOUT  = 10

EMAIL_HOST_USER      = 'edutrellisprivatelimited@gmail.com'
EMAIL_HOST_PASSWORD  = 'tnjwlzgzmnexoufo'
DEFAULT_FROM_EMAIL   = f'EduTrellis <{EMAIL_HOST_USER}>'
LEAD_RECIPIENT_EMAIL = EMAIL_HOST_USER

# ── SMS OTP (2Factor.in) ─────────────────────────────────────────────────────
# Signup/profile phone verification goes over SMS via this API key — a plain
# HTTPS call, so it isn't affected by the Gmail/Titan SMTP delivery problems
# or by Railway potentially blocking outbound SMTP on production.
TWO_FACTOR_API_KEY = '12feb4c9-9636-11f1-9cb1-0200cd936042'

# ── AI Chat (NVIDIA API) ─────────────────────────────────────────────────────
# Powers the public /AI/ chat page (myapp/ai_chat.py). This is a real,
# billable API key — hardcoded here at the user's explicit choice, same as
# the credentials above, which means it's visible in this repo's git
# history to anyone with access. Rotate it in the NVIDIA console if it ever
# needs to change.
NVIDIA_API_KEY = os.environ.get('NVIDIA_API_KEY', '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').strip()
NVIDIA_CHAT_MODEL = os.environ.get('NVIDIA_CHAT_MODEL', 'nvidia/nemotron-3.5-lightning-30b-a3b').strip()
# Spare keys for the same endpoint. One key being rate-limited, out of
# credit, or revoked shouldn't take the whole chat down, so ai_chat tries
# these in order after the primary above (see _nvidia_key_pool there).
# Same trade-off as NVIDIA_API_KEY: real, billable credentials kept in the
# repo at the project owner's explicit choice, so they're visible in git
# history to anyone with access — rotate them in the NVIDIA console.
NVIDIA_FALLBACK_API_KEYS = [
    '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',
    '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',
]
# NVIDIA_API_KEYS overrides the whole ordered pool at once (comma-separated)
# for deployments that would rather not carry the hardcoded spares.
_nvidia_key_env = os.environ.get('NVIDIA_API_KEYS', '').strip()
if _nvidia_key_env:
    _nvidia_keys = _nvidia_key_env.split(',')
else:
    _nvidia_keys = [NVIDIA_API_KEY] + NVIDIA_FALLBACK_API_KEYS
NVIDIA_API_KEYS = list(dict.fromkeys(k.strip() for k in _nvidia_keys if k.strip()))

# Nemotron 3 Super (120B) — its own dedicated key rather than a member of the
# pool above, since pool access to the Lightning endpoint says nothing about
# invoke access to this one. Same hardcoding trade-off as the keys above.
_nemotron_super_key_file = BASE_DIR / '.secrets' / 'nvidia_nemotron_super_api_key'
NVIDIA_NEMOTRON_SUPER_API_KEY = os.environ.get(
    'NVIDIA_NEMOTRON_SUPER_API_KEY',
    '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',
).strip()
if not NVIDIA_NEMOTRON_SUPER_API_KEY and _nemotron_super_key_file.is_file():
    NVIDIA_NEMOTRON_SUPER_API_KEY = _nemotron_super_key_file.read_text(encoding='utf-8').strip()
# Intentionally hardcoded at the project owner's request.
NVIDIA_FLUX_API_KEY = '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'

# ChatGPT 5.6 Terra — its own dedicated key against nemotron-3-ultra-550b-a55b,
# same trade-off as NVIDIA_NEMOTRON_SUPER_API_KEY above (not part of the
# shared pool, since pool access says nothing about invoke access to this
# endpoint). Intentionally hardcoded at the project owner's request.
_terra_key_file = BASE_DIR / '.secrets' / 'nvidia_terra_api_key'
NVIDIA_TERRA_API_KEY = os.environ.get(
    'NVIDIA_TERRA_API_KEY',
    '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',
).strip()
if not NVIDIA_TERRA_API_KEY and _terra_key_file.is_file():
    NVIDIA_TERRA_API_KEY = _terra_key_file.read_text(encoding='utf-8').strip()
NVIDIA_FLUX_EDIT_API_KEY = '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'

# ── Cloudflare Workers AI (image models) ────────────────────────────────────
# Backs the SDXL Lightning / Flux 1 Schnell / SDXL Base / DreamShaper 8 LCM
# picker options (myapp/image_generation.py). Same hardcoding trade-off as
# the keys above — intentionally hardcoded at the project owner's request.
CLOUDFLARE_ACCOUNT_ID = os.environ.get(
    'CLOUDFLARE_ACCOUNT_ID', 'e6e651b3aa7f473cce2cf81eeeafcfc8',
).strip()
CLOUDFLARE_API_TOKEN = os.environ.get(
    'CLOUDFLARE_API_TOKEN', 'cfut_ZI5Am6F16CgLJpggh6NjHgCyPliNyDiMjLZiGWwIec9f322b',
).strip()

# Backs the "Gemini 2.5 Flash" picker option (myapp/ai_chat.py) — called
# through Google's OpenAI-compatible endpoint, not the native generateContent
# REST API, so it can reuse the existing chat streaming pipeline. Same
# hardcoding trade-off as the keys above — intentionally hardcoded at the
# project owner's request.
GEMINI_API_KEY = os.environ.get(
    'GEMINI_API_KEY', 'AQ.Ab8RN6LjJgl8ECIgKRLcyq9PaeWtiYbf5jskVN7K2y3NM6yZuA',
).strip()

# Backs the OpenRouter picker options (myapp/ai_chat.py) — OpenRouter's REST
# API is itself OpenAI-compatible, so this reuses the existing chat streaming
# pipeline the same way Gemini does (see _OPENROUTER_BASE_URL there). Same
# hardcoding trade-off as the keys above — intentionally hardcoded at the
# project owner's request.
OPENROUTER_API_KEY = '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'

# Tavily powers optional live web search from the AI chat composer.
TAVILY_API_KEY = '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'

# ── Dropbox archive for AI-generated images ──────────────────────────────────
# Every image the AI generates is mirrored to /vidhyora/<user email>/ in this
# Dropbox account (myapp/dropbox_images.py), because local media storage is
# wiped on every redeploy. Uploading happens on a background thread, so this
# adds nothing to image reply times.
#
# Hardcoded at the project owner's explicit request, like the keys above —
# which means a refresh token with full access to that Dropbox account is
# visible to anyone who can read this repo or its git history. Rotate it from
# the Dropbox App Console if that ever stops being acceptable.
#
# These are separate from the dashboard-configured DropboxSettings row that
# dropbox_backup.py uses for db.sqlite3 backups; the two write to different
# folders and neither can disturb the other.
DROPBOX_APP_KEY = 'wgg2fsw5pf16x8q'
DROPBOX_APP_SECRET = '38dg9gi6djz3zuu'
DROPBOX_REFRESH_TOKEN = 'Si57f7yXuB0AAAAAAAAAAZGrsYbd1YLQpvGHxlJES4DRvKr7mDfZo8xqLaJBTY_s'

# Master switch, off while the test suite runs. Tests exercise the real image
# and report views, and those now archive to Dropbox — without this, running
# `manage.py test` uploads the suite's fake images into the live account (it
# did exactly that once). Tests that mean to cover archiving turn it back on
# with override_settings and patch the client, so they never touch the network.
DROPBOX_IMAGE_ARCHIVE_ENABLED = not (
    'test' in sys.argv
    or os.path.basename(sys.argv[0] if sys.argv else '').startswith(('pytest', 'py.test'))
)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Expose the AI latency breakdown added in views.py/ai_chat.py in the normal
# development and Gunicorn logs.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'myapp': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


