# Generated by Django 5.2.12 on 2026-08-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart_storeprofile_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
