# Generated by Django 5.2.12 on 2026-08-08 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_orders_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('badge_title', models.CharField(default='Working since 2020', max_length=120)),
                ('badge_subtitle', models.CharField(default='Websites & technical services · store launched 2026', max_length=200)),
                ('founder_name', models.CharField(default='Vijay Tiwari', max_length=120)),
                ('founder_title', models.CharField(default='Founder & CEO', max_length=120)),
                ('founder_email', models.EmailField(default='ceo@edutrellis.in', max_length=254)),
                ('founder_linkedin', models.URLField(blank=True, default='https://www.linkedin.com/in/vijaytiwariii/')),
                ('founder_photo', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('stat1_value', models.CharField(default='2020', max_length=20)),
                ('stat1_label', models.CharField(default='Founded', max_length=40)),
                ('stat2_value', models.CharField(default='1200+', max_length=20)),
                ('stat2_label', models.CharField(default='Clients', max_length=40)),
                ('stat3_value', models.CharField(default='500+', max_length=20)),
                ('stat3_label', models.CharField(default='Projects', max_length=40)),
                ('stat4_value', models.CharField(default='98%', max_length=20)),
                ('stat4_label', models.CharField(default='Satisfaction', max_length=40)),
                ('heading', models.CharField(default='A gadget store run by a tech company', max_length=200)),
                ('paragraph1', models.TextField(default='EduTrellis Private Limited has been working since 2020 — building and selling websites, and running the technical services around them: hosting, SEO, digital marketing and Google Business, for clients across India from our base in Lucknow.')),
                ('paragraph2', models.TextField(default="Along the way we bought a lot of gear for our own team and for clients, and got tired of spec sheets that didn't match reality. So this year we launched the store. Everything listed here is stock we keep, unbox and test before it ships, sold at a fixed price.")),
                ('list_heading', models.CharField(default='What you get with every order', max_length=150)),
                ('bullet_points', models.TextField(default='Sealed, genuine units, tested before dispatch\nSpecs listed honestly — real battery and charging numbers\nDispatch within 24 hours, tracking sent on WhatsApp\nGST invoice on request for business purchases\nA human who actually answers your messages', help_text='One point per line.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Content',
                'verbose_name_plural': 'About Us Content',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_key_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=100)),
                ('is_razorpay_enabled', models.BooleanField(default=False)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('refund', 'Refund Policy'), ('shipping', 'Shipping & Delivery')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(help_text='Plain text — a blank line starts a new paragraph.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policy Page',
                'verbose_name_plural': 'Policy Pages',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay')], default='cod', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cod_pending', 'COD — pay on delivery')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=80)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='myapp.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used as the product ID in the cart/orders — keep it stable once orders exist.', max_length=40, unique=True)),
                ('brand', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(help_text='Shown on the product card.', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Longer description shown when a shopper opens the product detail view.')),
                ('specs', models.TextField(blank=True, help_text="One spec per line, formatted as 'Label: Value' — shown on the product detail view.")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Optional. Falls back to the icon + gradient tile below when left blank.', null=True, upload_to='products/')),
                ('icon', models.CharField(default='fa-box', help_text="Font Awesome icon class shown when no image is set, e.g. 'fa-headphones'.", max_length=60)),
                ('gradient', models.CharField(default='linear-gradient(135deg,#e8001e,#c0001a)', help_text='CSS background used behind the icon when no image is set.', max_length=200)),
                ('flag', models.CharField(blank=True, help_text="Small badge on the card, e.g. 'Bestseller'.", max_length=40)),
                ('stock_status', models.CharField(default='In stock', help_text="e.g. 'In stock', 'Only 4 left'.", max_length=40)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated, e.g. 'ANC, 40h battery, IPX5'.", max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.category')),
            ],
            options={
                'verbose_name': 'Store Product',
                'verbose_name_plural': 'Store Products',
                'ordering': ['order', 'name'],
            },
        ),
    ]
