# Generated by Django 5.2.12 on 2026-08-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_product_video_alter_product_image_productcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(blank=True, max_length=200)),
                ('app_secret', models.CharField(blank=True, max_length=200)),
                ('refresh_token', models.CharField(blank=True, max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dropbox Backup Settings',
                'verbose_name_plural': 'Dropbox Backup Settings',
            },
        ),
    ]
