# Generated by Django 5.2.12 on 2026-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_dropboxsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlead',
            name='source',
            field=models.CharField(choices=[('edutrellis', 'edutrellis.in'), ('store', 'edutrellis.in/store'), ('websitecreation', 'edutrellis.in/websitecreation')], default='edutrellis', max_length=20),
        ),
    ]
