# Generated by Django 5.2.12 on 2026-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_order_address_line1_order_address_line2_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text="Use these settings instead of the server's default email configuration.")),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.CharField(blank=True, help_text='e.g. "EduTrellis <support@edutrellis.in>". Defaults to the SMTP username if left blank.', max_length=200)),
                ('notify_email', models.EmailField(blank=True, help_text='Where new-order and contact-lead notifications are sent. Defaults to the support email if left blank.', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email (SMTP) Settings',
                'verbose_name_plural': 'Email (SMTP) Settings',
            },
        ),
    ]
