# Generated by Django 5.2.12 on 2026-08-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_emailverification_delete_signupotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text="Show the 'Install App' option on the storefront. Needs an icon set below to actually work.")),
                ('app_name', models.CharField(default='EduTrellis Store', help_text='Full name shown during install and on the splash screen.', max_length=100)),
                ('short_name', models.CharField(default='EduTrellis', help_text='Short name shown under the home-screen icon.', max_length=40)),
                ('description', models.CharField(blank=True, default='Shop gadgets from EduTrellis — audio, wearables, charging and more.', max_length=200)),
                ('icon', models.ImageField(blank=True, help_text='Square logo, ideally 512×512px or larger — used as the installed app icon.', null=True, upload_to='pwa/')),
                ('theme_color', models.CharField(default='#e8001e', help_text='Hex color, e.g. #e8001e — used for the browser/app toolbar.', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex color shown behind the splash screen while the app loads.', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PWA (Install App) Settings',
                'verbose_name_plural': 'PWA (Install App) Settings',
            },
        ),
    ]
