# Generated by Django 5.2.12 on 2026-08-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_pwasettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Flat delivery fee per order. Leave 0 for free delivery.', max_digits=10)),
                ('free_delivery_over', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Orders at or above this subtotal skip the delivery fee above, even if one is set. Leave 0 to always charge it (if set).', max_digits=10)),
                ('handling_fee', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Flat handling fee per order. Leave 0 for no handling fee.', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery & Handling Fees',
                'verbose_name_plural': 'Delivery & Handling Fees',
            },
        ),
    ]
