# Generated by Django 5.2.12 on 2026-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_aiconversation_session_key_alter_aiconversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='image_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='model_key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
