# Generated by Django 5.2.12 on 2026-08-15 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_aimessage_image_data_aimessage_model_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('github_username', models.CharField(blank=True, max_length=120)),
                ('repo_full_name', models.CharField(blank=True, help_text="owner/repo this connection reads/writes, e.g. 'boosternotes/EduTrellis'.", max_length=200)),
                ('default_branch', models.CharField(blank=True, default='main', max_length=100)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GitHub Connection',
                'verbose_name_plural': 'GitHub Connections',
            },
        ),
    ]
