# Generated by Django 5.2.12 on 2026-08-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_githubconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
