# Generated by Django 5.2.12 on 2026-08-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_aimessage_document_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text="Short label/question this answers, e.g. 'refund policy' or 'GST registration steps'.", max_length=200)),
                ('content', models.TextField(help_text='The saved text EduTrellis Light will answer from.')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('web_search', 'Web search')], default='manual', max_length=20)),
                ('source_url', models.URLField(blank=True, help_text='Where this was found, if saved from a web search.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entries (EduTrellis Light)',
                'ordering': ['-updated_at'],
            },
        ),
    ]
