# Generated by Django 5.2.12 on 2026-08-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_knowledgeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('web_search', 'Web search'), ('chat', 'Chat')], default='manual', max_length=20),
        ),
    ]
