# Generated by Django 5.2.12 on 2026-08-16 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_knowledgeentry_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Same idea as user, for a private entry saved from a guest (not logged in) session.', max_length=40),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Set only for an entry private to one logged-in person (from a file/image upload, or their own account details). Blank = visible to everyone.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
