# Generated by Django 5.2.12 on 2026-08-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_seed_knowledge_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='product_slugs',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
