# Generated by Django 5.2.12 on 2026-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_aimessage_product_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='document_text',
            field=models.TextField(blank=True),
        ),
    ]
