# Generated by Django 5.2.12 on 2026-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_aimessage_document_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ai_subscription_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='ai_free_messages_used',
            field=models.PositiveIntegerField(default=0, help_text='Free-tier EduTrellis AI messages sent so far (resets on each new subscription purchase).'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='ai_subscription_until',
            field=models.DateTimeField(blank=True, help_text='EduTrellis AI access is unlimited until this time. Blank/past = free tier.', null=True),
        ),
    ]
