# Generated by Django 5.2.12 on 2026-08-18 04:59

from django.db import migrations, models

# Matches models.AI_SUBSCRIPTION_PRODUCT_SLUG — kept as a literal (same
# reasoning as 0030_seed_knowledge_base.py: historical models from
# apps.get_model() don't carry over module-level constants, only fields).
AI_PRODUCT_SLUG = 'edutrellis-ai-monthly'


def mark_ai_product_digital(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    Product.objects.filter(slug=AI_PRODUCT_SLUG).update(is_digital=True)


def unmark_ai_product_digital(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    Product.objects.filter(slug=AI_PRODUCT_SLUG).update(is_digital=False)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_seed_ai_subscription_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False, help_text='Digital/subscription product — nothing physically ships, so checkout hides Cash on Delivery for it.'),
        ),
        migrations.RunPython(mark_ai_product_digital, unmark_ai_product_digital),
    ]
