# Generated by Django 5.2.12 on 2026-08-18 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_fix_rudra_role_knowledge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AIBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Block',
                'verbose_name_plural': 'AI Blocks',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ip_address__isnull', False), ('user__isnull', False), _connector='OR'), name='aiblock_ip_or_user_required')],
            },
        ),
    ]
