# Generated by Django 5.2.12 on 2026-08-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_rebrand_vidhyora_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, help_text='Browser-tab icon. Square, ideally 512×512px or smaller (PNG/ICO). Leave blank to use the default EduTrellis favicon.', null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Customization',
                'verbose_name_plural': 'Site Customization',
            },
        ),
    ]
