# Generated by Django 5.2.12 on 2026-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_activeusersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='user_prompt',
            field=models.TextField(blank=True),
        ),
    ]
