# Generated by Django 5.2.12 on 2026-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_sitecustomization_social_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgeentry',
            options={
                'ordering': ['-updated_at'],
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entries (legacy — unused)',
            },
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='content',
            field=models.TextField(
                help_text='Saved text from the retired EduTrellis Light feature — no longer used by any AI reply.',
            ),
        ),
    ]
