# Generated by Django 5.2.12 on 2026-09-15 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_seed_default_superuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAPIAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_keys', models.CharField(blank=True, help_text='Comma-separated ai_chat.MODELS keys (e.g. "sol,terra,luna") this account\'s API key may call.', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Staff account that last changed this grant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_api_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI API Access Grant',
                'verbose_name_plural': 'AI API Access Grants',
            },
        ),
        migrations.CreateModel(
            name='AIAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First few characters, shown in the UI so the user can recognize their key.', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_api_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI API Key',
                'verbose_name_plural': 'AI API Keys',
            },
        ),
    ]
